# docker compose up nodered -d
version: "3.9"

services:
  nodered:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gb-nodered
    ports:
      - "1880:1880"
    volumes:
      - node_red_data:/data
      - ./flows.json:/data/flows.json
    restart: unless-stopped

volumes:
  node_red_data:
