# docker compose up -d
services:
  mosquitto:
    build:
      context: ./mosquitto
      dockerfile: Dockerfile
    container_name: gb-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    restart: unless-stopped

  nodered:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gb-nodered
    ports:
      - "1880:1880"
    volumes:
      - node_red_data:/data
      - ./flows.json:/data/flows.json
    depends_on:
      - mosquitto
    restart: unless-stopped

volumes:
  node_red_data:
  mosquitto_data:
  mosquitto_log:
